sonar.projectKey=steavenspr_skillhub_groupe
sonar.organization=steavenspr

sonar.sources=backend/app,backend/config,backend/database,backend/routes
sonar.tests=backend/tests
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,backend/tests/**
