sonar.projectKey=steavenspr_skillhub_groupe
sonar.organization=steavenspr

sonar.sources=backend/app,backend/config,backend/database,backend/routes,frontend/src
sonar.tests=backend/tests
sonar.coverageReportPaths=backend/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**,backend/tests/**,frontend/dist/**,frontend/coverage/**
