sonar.projectKey=steavenspr_skillhub_groupe
sonar.organization=steavenspr

sonar.sources=backend
sonar.tests=backend/tests
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**
